# Generated by Django 5.2.11 on 2026-02-10 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_malicious', models.BooleanField(default=False)),
                ('balance', models.FloatField(default=0.0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('reputation', models.FloatField(default=100.0)),
                ('packets_sent', models.IntegerField(default=0)),
                ('packets_received', models.IntegerField(default=0)),
                ('packets_dropped', models.IntegerField(default=0)),
                ('trade_success_count', models.IntegerField(default=0)),
                ('trade_failure_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_nodes', models.IntegerField(default=5)),
                ('difficulty', models.IntegerField(default=2)),
                ('min_delay', models.FloatField(default=0.1, help_text='Min network delay in seconds')),
                ('max_delay', models.FloatField(default=0.5, help_text='Max network delay in seconds')),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain_sim.node')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MetricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='blockchain_sim.node')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.FloatField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('nonce', models.IntegerField(default=0)),
                ('validator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain_sim.node')),
            ],
            options={
                'ordering': ['-index'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('timestamp', models.FloatField()),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='blockchain_sim.block')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_txs', to='blockchain_sim.node')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_txs', to='blockchain_sim.node')),
            ],
        ),
    ]
